name: "Jira Issue Key Checker"
on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: HLX-automation/GJA-PR-Actions@v1
        with:
          GITHUB_TOKEN: ${{ secrets.TOKEN_FOR_GITHUB }}
          jira-prefix: "ABC"